package com.kamarkaka.leetcode;

/***
 * 389. Find the Difference
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 * Example 1:
 *   Input: s = "abcd", t = "abcde"
 *   Output: "e"
 *   Explanation: 'e' is the letter that was added.
 * Example 2:
 *   Input: s = "", t = "y"
 *   Output: "y"
 * Constraints:
 *   0 <= s.length <= 1000
 *   t.length == s.length + 1
 *   s and t consist of lowercase English letters.
 */
public class LC0389 {
    public char findTheDifference(String s, String t) {
        if (s.length() == 0) return t.charAt(0);

        int[] count = new int[26];

        for (char c : s.toCharArray()) {
            count[c - 'a']++;
        }

        for (char c : t.toCharArray()) {
            if (count[c - 'a'] == 0) return c;

            count[c - 'a']--;
        }

        return t.charAt(t.length() - 1);
    }
}
